/**
 * Vercel / CI：在发布前将 VITE_* 写入 ui/lumina-env.auto.js，供纯静态（无 Vite 打包）站点在运行时使用 globalThis.__LUMINA_ENV__。
 * 在 Vercel 项目环境变量中配置：VITE_SUPABASE_URL、VITE_SUPABASE_ANON_KEY（及按需 VITE_LUMINA_AUTH_USE_DEMO）。
 * @see ui/integrations/supabaseClient.js readEnvString
 */
import { writeFileSync } from "fs";
import { dirname, join } from "path";
import { fileURLToPath } from "url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const outFile = join(__dirname, "../ui/lumina-env.auto.js");

const pick = (name) => {
  const v = process.env[name];
  if (v == null || String(v).trim() === "") {
    return undefined;
  }
  return String(v);
};

const o = {
  VITE_SUPABASE_URL: pick("VITE_SUPABASE_URL"),
  VITE_SUPABASE_ANON_KEY: pick("VITE_SUPABASE_ANON_KEY"),
  VITE_LUMINA_AUTH_USE_DEMO: pick("VITE_LUMINA_AUTH_USE_DEMO"),
};

/** 仅写入有值的键，避免覆写为 undefined。 */
const flat = Object.fromEntries(Object.entries(o).filter(([, v]) => v !== undefined));

const json = JSON.stringify(flat, null, 0);
const body = `/* Auto-generated by scripts/vercel-build.mjs. Do not commit real keys into Git. */\n` +
  `(function(){\n` +
  `  if (typeof globalThis === "undefined") return;\n` +
  `  globalThis.__LUMINA_ENV__ = Object.assign(\n` +
  `    {},\n` +
  `    typeof globalThis.__LUMINA_ENV__ === "object" && globalThis.__LUMINA_ENV__ ? globalThis.__LUMINA_ENV__ : {},\n` +
  `    ${json}\n` +
  `  );\n` +
  `})();\n`;

writeFileSync(outFile, body, "utf8");
const keys = Object.keys(flat);
console.log(
  keys.length
    ? `[Lumina] vercel-build: wrote lumina-env.auto.js (keys: ${keys.join(", ")})`
    : "[Lumina] vercel-build: wrote lumina-env.auto.js (no VITE_SUPABASE_* in process.env; check Vercel env)"
);
