/* Auto-generated by scripts/vercel-build.mjs. Do not commit real keys into Git. */
(function(){
  if (typeof globalThis === "undefined") return;
  globalThis.__LUMINA_ENV__ = Object.assign(
    {},
    typeof globalThis.__LUMINA_ENV__ === "object" && globalThis.__LUMINA_ENV__ ? globalThis.__LUMINA_ENV__ : {},
    {}
  );
})();
